txt_path: ../data/owt_train.txt
bpe_path: ../data/owt_train.txt.bpe
bpe_shape_path: ../data/owt_train.txt.bpe.shape
valid_txt_path: ../data/owt_valid.txt
valid_bpe_path: ../data/owt_valid.txt.bpe
valid_bpe_shape_path: ../data/owt_valid.txt.bpe.shape
vocab_path: ../data/owt.vocab
merges_path: ../data/owt.merges
checkpoint_file: ../data/owt_train.txt.checkpoint
validation_checkpoint_file: ../data/owt_train.txt.best.checkpoint
vocab_size: 32000
context_length: 256
d_model: 512
d_ff: 1344
rope_theta: 10000
num_layers: 4
num_heads: 16
batch_size: 32
num_batches: 4
training_steps: 1250
max_lr: 0.01
min_lr: 0.001