txt_path: ../data/TinyStoriesV2-GPT4-train.txt
valid_txt_path: ../data/TinyStoriesV2-GPT4-valid.txt
bpe_path: ../data/TinyStoriesV2-GPT4-train.txt.bpe
bpe_shape_path: ../data/TinyStoriesV2-GPT4-train.txt.bpe.shape
valid_bpe_path: ../data/TinyStoriesV2-GPT4-valid.txt.bpe
valid_bpe_shape_path: ../data/TinyStoriesV2-GPT4-valid.txt.bpe.shape
vocab_path: ../data/TinyStoriesV2-GPT4-train.txt.vocab
merges_path: ../data/TinyStoriesV2-GPT4-train.txt.merges
checkpoint_file: ../data/TinyStoriesV2-GPT4-train.txt.checkpoint
validation_checkpoint_file: ../data/TinyStoriesV2-GPT4-train.txt.best.checkpoint
vocab_size: 10000
context_length: 256
d_model: 512
d_ff: 1344
rope_theta: 10000
num_layers: 4
num_heads: 16
batch_size: 64
num_batches: 2
training_steps: 1250
max_lr: 0.01
min_lr: 0.001